export { PrismaService } from "./prisma.service.js";

export { Prisma } from "@prisma/client";

export type {
  User,
  RefreshSession,
  Store,
  StoreUser,
  Device,
  Category,
  Brand,
  Product,
  ProductBarcode,
  InventoryBatch,
  StockMovement,
  StockAdjustment,
  Supplier,
  PurchaseOrder,
  PurchaseItem,
  Customer,
  Sale,
  SaleItem,
  Payment,
  Invoice,
  InvoiceSequence,
  Refund,
  RefundItem,
  Promotion,
  PromotionRule,
  IdempotencyKey,
  SyncEvent,
  AuditLog,
} from "@prisma/client";

export {
  SystemRole,
  UserStatus,
  StoreStatus,
  StoreUserRole,
  StoreUserStatus,
  InvitationStatus,
  DeviceType,
  ArchiveStatus,
  BatchStatus,
  StockMovementType,
  StockReferenceType,
  PurchaseOrderStatus,
  SaleStatus,
  PaymentStatus,
  SaleSource,
  PaymentMethod,
  PaymentRecordStatus,
  InvoiceStatus,
  RefundStatus,
  PromotionType,
  PromotionStatus,
  IdempotencyStatus,
  SyncStatus,
} from "@prisma/client";
